{% set name = "pyhanko-certvalidator" %}
{% set version = "0.26.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyhanko-certvalidator-{{ version }}.tar.gz
  sha256: d3ad4169aca30c0ffb7f30df045fd99fe18897a3ad38e03b1c29152e513d4dca

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - asn1crypto >=1.5.0
    - cryptography >=3.3.1
    - oscrypto >=1.1.0
    - requests >=2.24.0
    - uritools >=3.0.1

test:
  imports:
    - pyhanko_certvalidator
    - pyhanko_certvalidator.fetchers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MatthiasValvekens/certvalidator
  summary: Validates X.509 certificates and paths; forked from wbond/certvalidator
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrakitin
