{% set name = "pyhanko-certvalidator" %}
{% set version = "0.26.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 673d98837d068299302dff5e1120f4b341c7cd72808e7054bd19a45b683fd9d4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - asn1crypto >=1.5.0
    - cryptography >=3.3.1
    - oscrypto >=1.1.0
    - requests >=2.24.0
    - uritools >=3.0.1

test:
  imports:
    - pyhanko_certvalidator
    - pyhanko_certvalidator.fetchers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MatthiasValvekens/certvalidator
  summary: Validates X.509 certificates and paths; forked from wbond/certvalidator
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrakitin
